jobs:
  include:
  # to add Kong Enterprise releases, check the Pongo docs
  - name: Kong CE 2.2.0
    env: KONG_VERSION=2.2.0

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
